[theme]
base = "light"
primaryColor = "#0D7664"
backgroundColor = "#F6F2E8"
secondaryBackgroundColor = "#ECEDE7"
textColor = "#142A31"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
